chat/urls.py
from django.urls import path, re_path

from .views import ThreadView, InboxView
app_name='chat'
urlpatterns=[
    path('chat',InboxView.as_view()),
    re_path(r"^(?P<username>[\w.@+-]+)", ThreadView.as_view()),
]

freelance/urls.py
from django.urls import path,re_path,include
from django.conf import settings
from django.conf.urls.static import static
from FreelanceApp.views import *
from django.contrib import admin
from django.views.generic import TemplateView
from chat.views import *
from django.conf.urls import url
urlpatterns = [
    path('', home),
    path('registration', registration),
    path('user/login', login_page),
    path('user/logout', logout_page),
    path('top', top),
    path('user/registration', create_user),
    path('new_task', new_task),
    path('my_tasks', my_tasks),
    path('all_tasks', all_tasks),
    path('task/<int:id>', task_info),
    path('user/create_task', create_task),
    path('user/info', my_info),
    path('user/<int:id>', user_info),
    path('change_pass', change_pass),
    path('remove_task/<int:id>', delete_task),
    path('change_status/<int:id>', change_status),
    path('user/change_info', change_info),
    path('admin/', admin.site.urls),
    path('messages/', include('chat.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

chat/models.py
from django.db import models

from django.conf import settings
from django.db import models
from django.db.models import Q


class ThreadManager(models.Manager):
    def by_user(self, user):
        qlookup = Q(first=user) | Q(second=user)
        qlookup2 = Q(first=user) & Q(second=user)
        qs = self.get_queryset().filter(qlookup).exclude(qlookup2).distinct()
        return qs

    def get_or_new(self, user, other_username):  # get_or_create
        username = user.username
        if username == other_username:
            return None
        qlookup1 = Q(first__username=username) & Q(second__username=other_username)
        qlookup2 = Q(first__username=other_username) & Q(second__username=username)
        qs = self.get_queryset().filter(qlookup1 | qlookup2).distinct()
        if qs.count() == 1:
            return qs.first(), False
        elif qs.count() > 1:
            return qs.order_by('timestamp').first(), False
        else:
            Klass = user.__class__
            user2 = Klass.objects.get(username=other_username)
            if user != user2:
                obj = self.model(
                    first=user,
                    second=user2
                )
                obj.save()
                return obj, True
            return None, False


class Thread(models.Model):
    first = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_first')
    second = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='chat_thread_second')
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = ThreadManager()

    @property
    def room_group_name(self):
        return f'chat_{self.id}'

    def broadcast(self, msg=None):
        if msg is not None:
            broadcast_msg_to_chat(msg, group_name=self.room_group_name, user='admin')
            return True
        return False


class ChatMessage(models.Model):
    thread = models.ForeignKey(Thread, null=True, blank=True, on_delete=models.SET_NULL)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='sender', on_delete=models.CASCADE)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

chat/forms.py
from django import forms


class ComposeForm(forms.Form):
    message = forms.CharField(
            widget=forms.TextInput(
                attrs={"class": "form-control"}
                )
            )

chat/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import render
from django.urls import reverse
from django.views.generic.edit import FormMixin

from django.views.generic import DetailView, ListView

from .forms import ComposeForm
from .models import Thread, ChatMessage


class InboxView(LoginRequiredMixin, ListView):
    template_name = 'chat/inbox.html'
    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)


class ThreadView(LoginRequiredMixin, FormMixin, DetailView):
    template_name = 'chat/thread.html'
    form_class = ComposeForm
    success_url = './'

    def get_queryset(self):
        return Thread.objects.by_user(self.request.user)

    def get_object(self):
        other_username  = self.kwargs.get("username")
        obj, created = Thread.objects.get_or_new(self.request.user, other_username)
        #obj = Thread.objects.get_or_new(self.request.user, other_username)
        if obj == None:
            print("Sos")
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()
        return context

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
            return render(request, "index.html")
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        thread = self.get_object()
        user = self.request.user
        message = form.cleaned_data.get("message")
        ChatMessage.objects.create(user=user, thread=thread, message=message)
        return super().form_valid(form)

templates/chat/inbox.html
{% extends "base.html" %}

{% block content %}


{% endblock %}

templates/chat/thread.html
{% extends "base2.html" %}

{% block content %}
<div class="container" style="margin-top: 80px; max-width: 800px;">
    <h3 id="top">Чат с {% if user != object.first %}<a href="/user/{{ object.first.id}}" class="user_href">{{ object.first }}{% else %}<a href="/user/{{ object.second.id}}" class="user_href">{{ object.second }}{% endif %}</a></h3>
    <small><a href="#form">в конец</a></small>
    <div class="chat-container p-3" id='chat-items'>
    {% for chat in object.chatmessage_set.all %}
    {% if user == chat.user %}
    <div class="row"><div class="col-sm-5 offset-md-7 mt-2"><div class="p-2 message_send">{{ chat.message }}</div></div></div>
    {% else %}
    <div class="row"><div class="col-sm-5 mt-2"><div class="p-2 message_get">{{ chat.message }}</div></div></div>
    {% endif %}
    {% endfor %}
    </div>

    <form class="mt-4 mb-5" id='form' method='POST'> {% csrf_token %}
        <input type="hidden" id="myUsername" value="{{ user.username }}" />
        {{ form.as_p }}
        <button type='submit' class='btn btn-info'>Отправить</button>
    </form>
</div>
{% endblock %}

{% block script %}

<script>
// websocket scripts
// console.log(window.location)
var loc = windows.location
var formData = $("#form")
var msgInput = $("#id_message")
var chatHolder = $("#chat-items")
var me = $("#myUsername").val()

var wsStart = 'ws://'
if (loc.protocol == 'http:'){
    wsStart = 'wss://'
}
var endpoint = wsStart + loc.host + loc.pathname

var socket = new WebSocket(endpoint)

socket.onmessage =function(e){
    console.log("message", e)
    var chatDataMsg = JSON.parse(e.data)
    chatHolder.append("<li>" + chatDataMsg.message + "от" + chatDataMsg.username + "</li>")
}
socket.onopen=function(e){
    console.log("open", e)
    formData.submit(function(event){
        event.preventDefault()
        var msgText =msgInput.val()
        chatHolder.append("<li>"+ msgText + "от" + me + "</li>")
        //var formDataSerialized =formData.serialize()
        var finalData = {
            'message' : msgText
        }
        socket.send(JSON.stringify(finalData))
       // msgInput.val("")
        formData[0].reset()
    })
}
socket.onerror=function(e){
    console.log("error", e)
}
socket.onclose=function(e){
    console.log("close", e)
}
</script>
{% endblock %}